version: '3'

services:
  pokedexapp:
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: Dockerfile
    image: nest-pokemon-api
    container_name: nest_pokemon_api
    restart: always
    ports:
      - ${PORT}:${PORT}
    environment:
      DB_NAME:
      DB_HOST: mongo
      DB_PORT: 27017
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      PORT: ${PORT}
    #DEFAULT_LIMIT: ${DEFAULT_LIMIT}
    # volumes:
    #   - ./:/var/www/pokedex

  mongo:
    image: mongo:5.0
    container_name: mongo_db_pokemon
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo_express_pokemon
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_PASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://${DB_USER}:${DB_PASSWORD}@mongo:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    links:
      - mongo
    restart: unless-stopped
    ports:
      - 8099:8081

volumes:
  mongodb_data:
